/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdministradorGeneral;

import EncargadoDeLaboratorio.frLogin;

/**
 *
 * @author CRUZ_2019
 */
public class frmMenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public frmMenuAdministrador() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnmenu = new rsbuttom.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        pnldespegable = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        btnNuevoEdificio = new rsbuttom.RSButtonMetro();
        btnModificarLab = new rsbuttom.RSButtonMetro();
        rSButtonMetro9 = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoLab = new rsbuttom.RSButtonMetro();
        btnModificarEdificio = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnnuevo = new rsbuttom.RSButtonMetro();
        btnmodificar = new rsbuttom.RSButtonMetro();
        btnCerrarSesion = new rsbuttom.RSButtonMetro();
        btnasignarOrd = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        btnmenu.setBackground(new java.awt.Color(153, 0, 51));
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdministradorGeneral/home.png"))); // NOI18N
        btnmenu.setColorHover(new java.awt.Color(153, 0, 51));
        btnmenu.setColorNormal(new java.awt.Color(153, 0, 51));
        btnmenu.setColorPressed(new java.awt.Color(153, 0, 51));
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmenuMousePressed(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdministradorGeneral/utec.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1453, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 70));

        pnldespegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnldespegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 630));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 1410, 660));

        btnNuevoEdificio.setBackground(new java.awt.Color(38, 38, 38));
        btnNuevoEdificio.setText("NUEVO");
        btnNuevoEdificio.setColorHover(new java.awt.Color(175, 29, 0));
        btnNuevoEdificio.setColorNormal(new java.awt.Color(38, 38, 38));
        btnNuevoEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 50));

        btnModificarLab.setBackground(new java.awt.Color(38, 38, 38));
        btnModificarLab.setText("MODIFICAR");
        btnModificarLab.setColorHover(new java.awt.Color(24, 152, 0));
        btnModificarLab.setColorNormal(new java.awt.Color(38, 38, 38));
        btnModificarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLabActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 50));

        rSButtonMetro9.setBackground(new java.awt.Color(38, 38, 38));
        rSButtonMetro9.setText("HISTORIAL");
        rSButtonMetro9.setColorHover(new java.awt.Color(1, 165, 165));
        rSButtonMetro9.setColorNormal(new java.awt.Color(38, 38, 38));
        jPanel1.add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 50));

        jPanel4.setBackground(new java.awt.Color(106, 106, 106));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR USUARIOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 40));

        btnNuevoLab.setBackground(new java.awt.Color(38, 38, 38));
        btnNuevoLab.setText("NUEVO");
        btnNuevoLab.setColorHover(new java.awt.Color(215, 79, 42));
        btnNuevoLab.setColorNormal(new java.awt.Color(38, 38, 38));
        btnNuevoLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLabActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 240, 50));

        btnModificarEdificio.setBackground(new java.awt.Color(38, 38, 38));
        btnModificarEdificio.setText("MODIFICAR");
        btnModificarEdificio.setColorHover(new java.awt.Color(93, 10, 40));
        btnModificarEdificio.setColorNormal(new java.awt.Color(38, 38, 38));
        btnModificarEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, 50));

        jPanel5.setBackground(new java.awt.Color(106, 106, 106));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GESTIONAR LABORATORIO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 40));

        jPanel6.setBackground(new java.awt.Color(106, 106, 106));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GESTIONAR EDIFICIO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 40));

        jPanel7.setBackground(new java.awt.Color(106, 106, 106));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GESTIONAR PROGRAMAS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, 40));

        btnnuevo.setBackground(new java.awt.Color(38, 38, 38));
        btnnuevo.setText("NUEVO");
        btnnuevo.setColorHover(new java.awt.Color(173, 16, 60));
        btnnuevo.setColorNormal(new java.awt.Color(38, 38, 38));
        btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnnuevoMousePressed(evt);
            }
        });
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 50));

        btnmodificar.setBackground(new java.awt.Color(38, 38, 38));
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setColorHover(new java.awt.Color(224, 182, 0));
        btnmodificar.setColorNormal(new java.awt.Color(38, 38, 38));
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 50));

        btnCerrarSesion.setBackground(new java.awt.Color(38, 38, 38));
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setColorHover(new java.awt.Color(93, 142, 36));
        btnCerrarSesion.setColorNormal(new java.awt.Color(38, 38, 38));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 240, 70));

        btnasignarOrd.setBackground(new java.awt.Color(38, 38, 38));
        btnasignarOrd.setText("ASIGNAR ORDENANZAS");
        btnasignarOrd.setColorHover(new java.awt.Color(5, 134, 154));
        btnasignarOrd.setColorNormal(new java.awt.Color(38, 38, 38));
        btnasignarOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarOrdActionPerformed(evt);
            }
        });
        jPanel1.add(btnasignarOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
       

        /*int posicion= this.pnldespegable.getX();
        if (posicion > -1)
        {
            Animacion.Animacion.mover_izquierda(0, -250, 2, 2, pnldespegable);
        }
        else
        {
            Animacion.Animacion.mover_derecha(-250,0, 2, 2, pnldespegable);
        }*/

    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnmenuMousePressed

    private void btnnuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnnuevoMousePressed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        frmUsuario_Nuevo form=new frmUsuario_Nuevo();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        frmModificar_Usuario form=new frmModificar_Usuario();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnasignarOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarOrdActionPerformed
        // TODO add your handling code here:
        frmAsiganar_Ordenanzas form=new frmAsiganar_Ordenanzas();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnasignarOrdActionPerformed

    private void btnNuevoLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLabActionPerformed
        // TODO add your handling code here:
        NuevoLab form=new NuevoLab();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnNuevoLabActionPerformed

    private void btnModificarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLabActionPerformed
        // TODO add your handling code here:
        ModificarLab form=new ModificarLab();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnModificarLabActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        frLogin form=new frLogin();
        form.setVisible(true);
        
        
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnNuevoEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEdificioActionPerformed
        // TODO add your handling code here:
        frmNuevo_Edificio form=new frmNuevo_Edificio();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnNuevoEdificioActionPerformed

    private void btnModificarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEdificioActionPerformed
        // TODO add your handling code here:
        frmModificar_Edificio form=new frmModificar_Edificio();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnModificarEdificioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCerrarSesion;
    private rsbuttom.RSButtonMetro btnModificarEdificio;
    private rsbuttom.RSButtonMetro btnModificarLab;
    private rsbuttom.RSButtonMetro btnNuevoEdificio;
    private rsbuttom.RSButtonMetro btnNuevoLab;
    private rsbuttom.RSButtonMetro btnasignarOrd;
    private rsbuttom.RSButtonMetro btnmenu;
    private rsbuttom.RSButtonMetro btnmodificar;
    private rsbuttom.RSButtonMetro btnnuevo;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pnldespegable;
    private rsbuttom.RSButtonMetro rSButtonMetro9;
    // End of variables declaration//GEN-END:variables
}
