/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EncargadoDeLaboratorio;

import static EncargadoDeLaboratorio.frmcrearprograma.listaprogramciones;
import com.google.gson.Gson;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tablas.Notificaciones;

/**
 *
 * @author CRUZ_2019
 */
public class frmCrearNotificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCrearNotificacion
     */
    Notificaciones objnotificaciones;
    public Integer totalregistros;
    DefaultTableModel modelo;
    Statement objEjecutaConsulta;

    public frmCrearNotificacion() {
        initComponents();

        objnotificaciones = new Notificaciones();
        modelo = new DefaultTableModel();

        lstregistros.setModel(modelo);

        mostrar("");
    }

    void limpiarcampos() {
        txtidnotificacion.setText("");
        txttiponotificacion.setText("");
        txtfrecuencia.setText("");
        txttipofrecuencia.setText("");
        txthorario.setText("");

    }

    void mostrar(String buscar) {
        // TODO add your handling code here:
        //Instanciar clase de la tabla

        Gson gson = new Gson();

        totalregistros = 0;
        //instansiar la clase Gson que convierte el Json a array en java
        //Gson gson = new Gson();
        //envio datos al metodo
        String url = "http://limpieza.azurewebsites.net/WS/API/notificacion/mostrar.php";

        //Ejecuto consulta con los parametros de link
        String elJson = objnotificaciones.consultaCrediencial(url);

        //convertir a objeto de java
        Notificaciones[] listado = gson.fromJson(elJson, Notificaciones[].class);
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("TIPO NOTIFICACION");
        modelo.addColumn("FRECUENCIA");
        modelo.addColumn("TIPO FRECUENCIA");
        modelo.addColumn("HORARIO");

        Vector fila;
        lstregistros.setModel(modelo);

        //PARA SABER CUANTOS REGISTROS EXISTEN
        //int cantidadRegistros = objUsuarios.getCantidadRegistros();
        //PARA CREAR REGISTROS POR REGISTROS
        //DE LA TABLA DE NUESTRA BASE DE DATOS
        for (Notificaciones registros : listado) {

            //CREAMOS UNA NUEVA FILA PARA LA TABLA
            fila = new Vector();
            // AGREGAMOS LA MISMA FILA PARA LA TABLA
            //A NUESTRO VECTOR

            //fila.add(indice);
            fila.add(registros.getIdNotificacion());
            fila.add(registros.getTipoNotificacion());
            fila.add(registros.getFrecuencia());
            fila.add(registros.getTipoFrecuencia());
            fila.add(registros.getHorario());

            //AGREGAMOS LA FILA COMPLETA DE DATOS
            //AL CONTENEDOR QUE ESTAMOS DIBUJANDO
            totalregistros++;
            modelo.addRow(fila);
        }
        lblregistros.setText("Total registros: " + Integer.toString(totalregistros));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtidnotificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttiponotificacion = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtfrecuencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttipofrecuencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthorario = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnbuscarhorarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstregistros = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtidnotibuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblregistros = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        fondo.setBackground(new java.awt.Color(121, 11, 42));

        jPanel1.setBackground(new java.awt.Color(173, 16, 60));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva notificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        txtidnotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnotificacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de notificacion:");

        txttiponotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttiponotificacionActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Frecuencia:");

        txtfrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfrecuenciaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de frecuencia:");

        txttipofrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipofrecuenciaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Horario:");

        txthorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorarioActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.GIF"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnbuscarhorarios.setText("...");
        btnbuscarhorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarhorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btncancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttipofrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthorario)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(txtidnotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscarhorarios)
                        .addGap(287, 287, 287))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttiponotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidnotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttiponotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtfrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttipofrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarhorarios)))
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOTIFICACIONES");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de notificaciones"));

        lstregistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lstregistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstregistrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstregistros);

        jLabel13.setText("Notificacion:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.gif"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        lblregistros.setText("Registros:");

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtidnotibuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblregistros)
                .addGap(88, 88, 88))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtidnotibuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnsalir)
                    .addComponent(btneliminar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblregistros)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidnotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnotificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnotificacionActionPerformed

    private void txttiponotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttiponotificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttiponotificacionActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        if (txtidnotificacion.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar un ID");
            txtidnotificacion.requestFocus();
            return;
        }
        if (txttiponotificacion.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar un tipo de notificacion");
            txttiponotificacion.requestFocus();
            return;
        }
        if (txthorario.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar una horario");
            txthorario.requestFocus();
            return;
        }

        Notificaciones func = new Notificaciones();

        String idnotificacion = txtidnotificacion.getText().toString().trim();
        String tiponotificacion = txttiponotificacion.getText().toString().trim();
        String frecuencia = txtfrecuencia.getText().toString().trim();
        String tipofecuencia = txttipofrecuencia.getText().toString().trim();
        String horario = txthorario.getText().toString().trim();

        String url = "http://limpieza.azurewebsites.net/WS/API/notificacion/actualizar.php";

        try {
            func.ActulizarDatos(url, idnotificacion, tiponotificacion, frecuencia, tipofecuencia, horario);
            JOptionPane.showMessageDialog(rootPane, "La notificacion se actualizo correctamente");
        } catch (Exception e) {
        }
        mostrar("");
        limpiarcampos();

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        limpiarcampos();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtfrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfrecuenciaActionPerformed

    private void txttipofrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipofrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipofrecuenciaActionPerformed

    private void txthorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorarioActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        if (txtidnotificacion.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar un ID");
            txtidnotificacion.requestFocus();
            return;
        }
        if (txttiponotificacion.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar un tipo de notificacion");
            txttiponotificacion.requestFocus();
            return;
        }
        if (txthorario.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes asignar una horario");
            txthorario.requestFocus();
            return;
        }
        Notificaciones func = new Notificaciones();

        String idnotificacion = txtidnotificacion.getText();
        String tiponotificacion = txttiponotificacion.getText().toString().trim();
        String frecuencia = txtfrecuencia.getText().toString().trim();
        String tipofecuencia = txttipofrecuencia.getText().toString().trim();
        String horario = txthorario.getText().toString().trim();

        String url = "http://limpieza.azurewebsites.net/WS/API/notificacion/insertar.php";

        try {
            func.InsertarUsuario(url, idnotificacion, tiponotificacion, frecuencia, tipofecuencia, horario);
            JOptionPane.showMessageDialog(rootPane, "La notificacion se inserto correctamente");
        } catch (Exception e) {
        }
        mostrar("");
        limpiarcampos();

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void lstregistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstregistrosMouseClicked
        // TODO add your handling code here:

        int fila = lstregistros.rowAtPoint(evt.getPoint());

        txtidnotificacion.setText(lstregistros.getValueAt(fila, 0).toString());
        txttiponotificacion.setText(lstregistros.getValueAt(fila, 1).toString());
        txtfrecuencia.setText(lstregistros.getValueAt(fila, 2).toString());
        txttipofrecuencia.setText(lstregistros.getValueAt(fila, 3).toString());
        txthorario.setText(lstregistros.getValueAt(fila, 4).toString());

    }//GEN-LAST:event_lstregistrosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        Gson gson = new Gson();
        Notificaciones func = new Notificaciones();

        String idnotificacion = txtidnotibuscar.getText();

        String url = "http://limpieza.azurewebsites.net/WS/API/notificacion/mostrarP.php?";

        String parametros = "idNotificacion=" + idnotificacion;

        //Ejecuto consulta con los parametros de link
        String elJson = "[" + func.consultaCrediencial(url + parametros) + "]";

        try {

            if (!txtidnotibuscar.getText().equals("")) {
                //Ejecuto consulta con los parametros de link

                //convertir a objeto de java
                Notificaciones[] listado = gson.fromJson(elJson, Notificaciones[].class);
                DefaultTableModel modelo;
                modelo = new DefaultTableModel();
                modelo.addColumn("ID");
                modelo.addColumn("TIPO NOTIFICACION");
                modelo.addColumn("FRECUENCIA");
                modelo.addColumn("TIPO FRECUENCIA");
                modelo.addColumn("HORARIO");

                Vector fila;

                //PARA SABER CUANTOS REGISTROS EXISTEN
                //int cantidadRegistros = objUsuarios.getCantidadRegistros();
                //PARA CREAR REGISTROS POR REGISTROS
                //DE LA TABLA DE NUESTRA BASE DE DATOS
                //CREAMOS UNA NUEVA FILA PARA LA TABLA
                fila = new Vector();
                // AGREGAMOS LA MISMA FILA PARA LA TABLA
                //A NUESTRO VECTOR

                //fila.add(indice);
                fila.add(listado[0].getIdNotificacion());
                fila.add(listado[0].getTipoNotificacion());
                fila.add(listado[0].getFrecuencia());
                fila.add(listado[0].getTipoFrecuencia());
                fila.add(listado[0].getHorario());

                //AGREGAMOS LA FILA COMPLETA DE DATOS
                //AL CONTENEDOR QUE ESTAMOS DIBUJANDO
                totalregistros++;
                modelo.addRow(fila);
                lstregistros.setModel(modelo);

            } else {
                mostrar("");
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtidnotificacion.getText().equals("")) 
        {
            int confirmacion =  JOptionPane.showConfirmDialog(rootPane,"Esta seguro de eliminar el programa","Confirmar",2);
            if (confirmacion==0)
            {{Notificaciones func = new Notificaciones();

        String idnotificacion = txtidnotificacion.getText().toString().trim();

        String url = "http://limpieza.azurewebsites.net/WS/API/notificacion/eliminar.php";

        try {
            func.EliminarDatos(url, idnotificacion);
            JOptionPane.showMessageDialog(rootPane, "La notificacion se elimino correctamente");
        } catch (Exception e) {
        }
        mostrar("");
        limpiarcampos();}}
            
        }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarhorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarhorariosActionPerformed
        // TODO add your handling code here:

        frmVistaHorarios form = new frmVistaHorarios();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnbuscarhorariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearNotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearNotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearNotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearNotificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearNotificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnbuscarhorarios;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblregistros;
    public static javax.swing.JTable lstregistros;
    private javax.swing.JTextField txtfrecuencia;
    public static javax.swing.JTextField txthorario;
    private javax.swing.JTextField txtidnotibuscar;
    private javax.swing.JTextField txtidnotificacion;
    private javax.swing.JTextField txttipofrecuencia;
    private javax.swing.JTextField txttiponotificacion;
    // End of variables declaration//GEN-END:variables
}
