/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EncargadoDeLaboratorio;

import static EncargadoDeLaboratorio.frmCrearhorarios.lstregistros;
import com.google.gson.Gson;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import tablas.Edificios;
import tablas.Laboratorios;
import tablas.Usuario;

/**
 *
 * @author CRUZ_2019
 */
public class frmVistaLaboratorios extends javax.swing.JFrame {

    /**
     * Creates new form frmVistaLaboratorios
     */
    DefaultTableModel contenedor;
    public frmVistaLaboratorios() {
        initComponents();
        this.setLocationRelativeTo(this);
         contenedor=new DefaultTableModel();
        contenedor.addColumn("ID");
        contenedor.addColumn("Nombre");
        contenedor.addColumn("Responsable");
        contenedor.addColumn("Capacidad");
        contenedor.addColumn("Ubicacion");
        
        
        listLaboratorios.setModel(contenedor);
        
        llenarTablaLaboratorios();
    }
   
    public void llenarTablaLaboratorios()
    {
        Laboratorios objLaboratorios=new Laboratorios();
        Vector fila;
        Gson gson=new Gson();
        String api="https://limpieza.azurewebsites.net/WS/API/consultasAdmin/tablaLab.php";
        
        String elJson=objLaboratorios.mostrarDatos(api);
        
        //convertimos a un obj de java
        Laboratorios[] losLaboratorios=gson.fromJson(elJson, Laboratorios[].class);
        
        for(Laboratorios registros: losLaboratorios)
        {
            fila=new Vector();
            fila.add(registros.getIdLaboratorio());
            fila.add(registros.getNombre());
            fila.add(registros.getResponsable());
            fila.add(registros.getCapacidad());
            fila.add(registros.getEdificio());
            
            contenedor.addRow(fila);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLaboratorios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de laboratorios"));

        listLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLaboratoriosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listLaboratoriosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listLaboratorios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLaboratoriosMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_listLaboratoriosMouseClicked

    private void listLaboratoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLaboratoriosMousePressed
        // TODO add your handling code here:
        
        if (evt.getClickCount()==2) {
            int fila=listLaboratorios.getSelectedRow();
            String cod;
            String valor;
            
            cod=listLaboratorios.getValueAt(fila, 0).toString();
             valor=listLaboratorios.getValueAt(fila, 1).toString();
            
            frmCrearhorarios.txtlaboratorio.setText(cod);
            frmCrearhorarios.txtnombrelabo.setText(valor);
            this.dispose();
            
        }
    }//GEN-LAST:event_listLaboratoriosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaLaboratorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listLaboratorios;
    // End of variables declaration//GEN-END:variables
}
